### ISSUE TITLE
Parse error? when trying to set to eth0

### ISSUE THREAD

**Issue by ryanluton** [JoeKuan/Network-Interfaces-Script#7]
`awk: ./bin/changeInterface.awk: line 5: illegal reference to local variable orders
awk: ./bin/changeInterface.awk: line 51: illegal reference to array pair
awk: ./bin/changeInterface.awk: line 155: illegal reference to variable fieldOrders`

Receiving this series of errors whenever I try to execute the changeInterface script. 

Have you ran across this before? I was looking for a simple way to wrap some networking changes around a node API and kept coming back to your scripts. 

Thanks much,

**Comment by JoeKuan** [comment]
Please can you attach the network interface file and the command line usage?

**Comment by ryanluton** [comment]
`awk -f ./bin/changeInterface.awk /etc/network/interfaces device=eth0 mode=dhcp`

and I have used your latest 
https://github.com/JoeKuan/Network-Interfaces-Script/blob/master/changeInterface.awk

Thanks.

**Comment by JoeKuan** [comment]
Sorry but I need your actual /etc/network/interfaces file to see what went wrong in my script. Please can you cut & paste the content or attach the file.

Cheers
Joe

**Comment by ryanluton** [comment]
http://pastebin.com/wkG7vPKE

**Comment by JoeKuan** [comment]
No, that is my awk script which I don't need. I need your /etc/network/interfaces file which contains all the network configurations of your machine.

**Comment by ryanluton** [comment]
Sorry I missed that. lol

```
auto lo
iface lo inet loopback

allow-hotplug eth0
iface eth0 inet static
address 10.1.100.24
gateway 10.1.100.1
netmask 255.255.255.0
dns-nameservers 10.1.100.1 8.8.8.8
```

**Comment by JoeKuan** [comment]
Ok, thanks. I have a look at the weekend and get back to you on Monday.

**Comment by ryanluton** [comment]
Appreciate it.

**Comment by JoeKuan** [comment]
Ok. It was non-POSIX compliant error. I have fixed it and committed the change.
